[tool.poetry]
name = "covid-movement"
version = "0.1.0"
description = ""
authors = ["Setu Shah <setu4993@yahoo.co.in>"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.4"
altair = "^4.1.0"
streamlit = "^0.60.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
