[tool.poetry]
name = "covid-mobility"
version = "0.1.0"
description = ""
authors = ["Setu Shah <setu+covid-movement@setu.me>"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.5"
altair = "^4.1.0"
streamlit = "^0.60.0"

[tool.poetry.dev-dependencies]
ipython = "^7.15.0"
black = "^19.10b0"
mypy = "^0.780"
isort = "^4.3.21"
autopep8 = "^1.5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
